#!/bin/busybox sh
/bin/busybox --install -s /bin

mount -t proc none /proc
mount -t sysfs none /sys
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

: "${SHELL:=/bin/sh}"
if [ -n "$export" ]; then
    EXPORTDEV=/dev/$export hostexport &
    unset export
fi
if [ -f /boot/rc ]; then
    . /boot/rc
fi

exec setsid -c "$SHELL" -i <>/dev/ttyS0 >&0 2>&1
